name: Reformatting & Linting

on: [push]

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Cache pre-commit paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~/.cache/pre-commit
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{
            hashFiles('.pre-commit-config.yaml') }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install-pre-commit
        run: python -m pip install --upgrade pre-commit

      - name: Run Pre-commit
        run: pre-commit run --all-files || (exit 0)

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Ran pre-commit: Reformatting & Linting" || (exit 0)

      - name: Run Pre-commit Checks
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Push changes
        run: git push
